### PR TITLE
Maintain source defaults

### PR DESCRIPTION
**Pull request by yeldah3**
Pre-populate source selector defaults for embedded and redirect sync flows

### CODE REVIEW

**Comment by utD9FeifNY6fLo35PfwlcznLtzQdMpBpXqBFeZ2** [comment]
<p><a href="https://linear.app/getcensus/issue/EMBED-442/add-redirect-flow-for-sync-management">EMBED-442 Add redirect flow for sync management</a></p>

**Comment by yeldah3** [comment]
* **#33** <a href="https://app.graphite.dev/github/pr/sutrolabs/census-embedded-demo/33?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @yeldah3 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by UOyXPJKtDj7BSXHeMVTcWvKtBkMK1h0hv7lAjh0** [comment]
### <span aria-hidden="true">✅</span> Deploy Preview for *powered-by-census-demo* ready!


|  Name | Link |
|:-:|------------------------|
|<span aria-hidden="true">🔨</span> Latest commit | 08315e6c2b6bd35e3ca24fd1a9aa38b221f84b43 |
|<span aria-hidden="true">🔍</span> Latest deploy log | https://app.netlify.com/sites/powered-by-census-demo/deploys/664d2870ac4d630007e10800 |
|<span aria-hidden="true">😎</span> Deploy Preview | [https://deploy-preview-33--powered-by-census-demo.netlify.app](https://deploy-preview-33--powered-by-census-demo.netlify.app) |
|<span aria-hidden="true">📱</span> Preview on mobile | <details><summary> Toggle QR Code... </summary><br /><br />QR Code<br /><br />_Use your smartphone camera to open QR code link._</details> |
---

_To edit notification comments on pull requests, go to your [Netlify site configuration](https://app.netlify.com/sites/powered-by-census-demo/configuration/deploys#deploy-notifications)._

**Review by LemonFace0309 — APPROVED** [review]
clean!

**Pull request merged**
