### PR TITLE
Support redirect flow for embedded sync management

### PR DESCRIPTION
**Pull request by yeldah3**
https://www.loom.com/share/01379db5bfd746c49532afbfe3bf442f

### CODE REVIEW

**Comment by utD9FeifNY6fLo35PfwlcznLtzQdMpBpXqBFeZ2** [comment]
<p><a href="https://linear.app/getcensus/issue/EMBED-442/add-redirect-flow-for-sync-management">EMBED-442 Add redirect flow for sync management</a></p>

**Comment by UOyXPJKtDj7BSXHeMVTcWvKtBkMK1h0hv7lAjh0** [comment]
### <span aria-hidden="true">✅</span> Deploy Preview for *powered-by-census-demo* ready!


|  Name | Link |
|:-:|------------------------|
|<span aria-hidden="true">🔨</span> Latest commit | 3dc6694ba747ece92ad90a17318e6dadd91afe10 |
|<span aria-hidden="true">🔍</span> Latest deploy log | https://app.netlify.com/sites/powered-by-census-demo/deploys/664d247664ff1700083bee4c |
|<span aria-hidden="true">😎</span> Deploy Preview | [https://deploy-preview-32--powered-by-census-demo.netlify.app](https://deploy-preview-32--powered-by-census-demo.netlify.app) |
|<span aria-hidden="true">📱</span> Preview on mobile | <details><summary> Toggle QR Code... </summary><br /><br />QR Code<br /><br />_Use your smartphone camera to open QR code link._</details> |
---

_To edit notification comments on pull requests, go to your [Netlify site configuration](https://app.netlify.com/sites/powered-by-census-demo/configuration/deploys#deploy-notifications)._

**Comment by yeldah3** [comment]
* **#32** <a href="https://app.graphite.dev/github/pr/sutrolabs/census-embedded-demo/32?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @yeldah3 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by LemonFace0309 — APPROVED** [review]
This is great

**Pull request merged**
