### PR TITLE
updated icon for redshift from amazon shopping to aws

### PR DESCRIPTION
**Pull request by LemonFace0309**
I think the approach of showing just "AWS" is better than showing the redshift icon because otherwise we'd also have to get custom icons for Google Sheets, BigQuery, etc.

CleanShot 2024-05-24 at 16 29 37@2x

### CODE REVIEW

**Comment by utD9FeifNY6fLo35PfwlcznLtzQdMpBpXqBFeZ2** [comment]
<p><a href="https://linear.app/getcensus/issue/EMBED-469/redshift-logo-should-be-redshift-not-amazon-shopping">EMBED-469 Redshift logo should be redshift, not amazon shopping</a></p>

**Comment by ZIxOozkggyhzlkZUTwcKB8W32wDEYU8dARxlISY** [comment]
* **#45** <a href="https://app.graphite.dev/github/pr/sutrolabs/census-embedded-demo/45?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @LemonFace0309 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by UOyXPJKtDj7BSXHeMVTcWvKtBkMK1h0hv7lAjh0** [comment]
### <span aria-hidden="true">✅</span> Deploy Preview for *powered-by-census-demo* ready!


|  Name | Link |
|:-:|------------------------|
|<span aria-hidden="true">🔨</span> Latest commit | dd761a825135720209c46cd940a8d7dc431dea46 |
|<span aria-hidden="true">🔍</span> Latest deploy log | https://app.netlify.com/sites/powered-by-census-demo/deploys/665122d4cb83170008e99673 |
|<span aria-hidden="true">😎</span> Deploy Preview | [https://deploy-preview-45--powered-by-census-demo.netlify.app](https://deploy-preview-45--powered-by-census-demo.netlify.app) |
|<span aria-hidden="true">📱</span> Preview on mobile | <details><summary> Toggle QR Code... </summary><br /><br />QR Code<br /><br />_Use your smartphone camera to open QR code link._</details> |
---

_To edit notification comments on pull requests, go to your [Netlify site configuration](https://app.netlify.com/sites/powered-by-census-demo/configuration/deploys#deploy-notifications)._

**Review by yeldah3 — APPROVED** [review]
this feels good to me!

**Pull request merged**
