### PR TITLE
add tooltip to sync readonly info and added documentation links to all tooltips

### PR DESCRIPTION
**Pull request by LemonFace0309**
CleanShot 2024-05-24 at 16 21 28@2x

Also added documentation links to all existing request tooltips

### CODE REVIEW

**Comment by utD9FeifNY6fLo35PfwlcznLtzQdMpBpXqBFeZ2** [comment]
<p><a href="https://linear.app/getcensus/issue/EMBED-468/hover-over-any-of-the-readonly-information-should-show-me-the-api-call">EMBED-468 Hover over any of the readonly information should show me the API call to retrieve it</a></p>

**Comment by ZIxOozkggyhzlkZUTwcKB8W32wDEYU8dARxlISY** [comment]
* **#47** <a href="https://app.graphite.dev/github/pr/sutrolabs/census-embedded-demo/47?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#46** <a href="https://app.graphite.dev/github/pr/sutrolabs/census-embedded-demo/46?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#44** <a href="https://app.graphite.dev/github/pr/sutrolabs/census-embedded-demo/44?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @LemonFace0309 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by UOyXPJKtDj7BSXHeMVTcWvKtBkMK1h0hv7lAjh0** [comment]
### <span aria-hidden="true">✅</span> Deploy Preview for *powered-by-census-demo* ready!


|  Name | Link |
|:-:|------------------------|
|<span aria-hidden="true">🔨</span> Latest commit | a9710e7caf754e7d987ff152cb07e26f189f3658 |
|<span aria-hidden="true">🔍</span> Latest deploy log | https://app.netlify.com/sites/powered-by-census-demo/deploys/6654281406ebf4000839d0e6 |
|<span aria-hidden="true">😎</span> Deploy Preview | [https://deploy-preview-44--powered-by-census-demo.netlify.app](https://deploy-preview-44--powered-by-census-demo.netlify.app) |
|<span aria-hidden="true">📱</span> Preview on mobile | <details><summary> Toggle QR Code... </summary><br /><br />QR Code<br /><br />_Use your smartphone camera to open QR code link._</details> |
---

_To edit notification comments on pull requests, go to your [Netlify site configuration](https://app.netlify.com/sites/powered-by-census-demo/configuration/deploys#deploy-notifications)._

**Review by yeldah3 — APPROVED** [review]
THIS IS SO GOOD, THE DOCS LINK!!!!! I am obsessed

**Pull request merged**
